/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.RetrieveApiResourcesResponse
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object APIEntryPointApi {

  /**
   * 此资源没有任何属性。而是以JSON正文中的链接形式提供初始API可用性。建议遵循&#39;curl&#39;链接值，[链接](https://tools.ietf.org/html/rfc5988)或位置标题，其中适用于检索资源,而不是构建自己的URL，以保持客户端与实现细节分离。
   * 
   * Expected answers:
   *   code 200 : RetrieveApiResourcesResponse 
   */
  def 检索API资源(): ApiRequest[RetrieveApiResourcesResponse] =
    ApiRequest[RetrieveApiResourcesResponse](ApiMethods.GET, "https://virtserver.swaggerhub.com/ten2net/NGSI/1.0.0", "/v2", "application/json  develop ccthAPI")
      .withSuccessResponse[RetrieveApiResourcesResponse](200)
      

}

