/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.GetAttributeValueResponse
import io.swagger.client.model.UpdateAttributeValueRequest
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object AttributeValueApi {

  /**
   * 请求有效负载是新的属性值。 *如果请求有效负载MIME类型是&#x60;application / json&#x60;，则属性的值设置为\\ n在有效负载中编码的JSON对象或数组(如果有效负载不是有效的JSON文档，则返回错误)。 *如果请求有效负载MIME类型为&#x60;text / plain&#x60;，则以下算法应用于有效负载： *如果有效载荷以引号(&#x60;\\“&#x60;)开头和结尾，则该值将被视为字符串\\ n(引文标记本身不被视为字符串的一部分) *如果为”true“或”false“ &#x60;，该值被视为布尔值。 *如果为&#x60;null&#x60;，则该值为空。 *如果前三个测试“失败”，则将文本解释为数字。 *如果不是一个有效的数字，然后返回一个错误，并且属性的值不变。请求中的有效负载MIME类型在&#x60;Content-Type&#x60; HTTP标头中指定。Response： *成功的操作使用204 No Content  *错误你选择非2xx和(可选)错误有效载荷。有关更多详细信息，请参阅“错误响应”部分。
   * 
   * Expected answers:
   *   code 200 :  
   * 
   * @param entityId 要更新的实体的ID。
   * @param attrName 属性名称
   * @param contentType 
   * @param body 
   * @param `type` 实体类型，以避免在存在多个具有相同实体ID的的情况下出现歧义。
   */
  def 更新属性值(entityId: String, attrName: String, contentType: String, body: UpdateAttributeValueRequest, `type`: Option[String] = None): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.PUT, "https://virtserver.swaggerhub.com/ten2net/NGSI/1.0.0", "/v2/entities/{entityId}/attrs/{attrName}/value", "application/json  develop ccthAPI")
      .withBody(body)
      .withQueryParam("type", `type`)
      .withPathParam("entityId", entityId)
      .withPathParam("attrName", attrName)
      .withHeaderParam("Content-Type", contentType)
      .withSuccessResponse[Unit](200)
        /**
   * 此操作返回带有属性值的&#x60;value&#x60;属性。 *如果属性值为JSON数组或对象： *如果&#x60;Accept&#x60;标题可以扩展为&#x60;application / json&#x60;或&#x60;text / plain&#x60;将值作为JSON返回，其响应类型为application / json或text / plain(取决于&#x60;Accept&#x60;标题中的第一个或者&#x60;&#x60;/ json&#x60;中的第一个，如果是&#x60;Accept：* / *&#x60;)。 *否则返回HTTP错误\\“406不可接受：接受的MIME类型：application / json，text / plain \\” *如果属性值是字符串，数字，null或布尔值： *如果&#x60;Accept&#x60;标题可以扩展为text / plain，则返回值为text。如果是字符串，则在开头和结尾使用引号标记。 *否则返回HTTP错误\\“406 Not Acceptable ：接受的MIME类型：text / plain \\“Response： *成功的操作使用200 OK。 *错误使用非2xx和(可选)错误有效负载。请参阅\\”错误响应\\“的小节更多细节。
   * 
   * Expected answers:
   *   code 200 : GetAttributeValueResponse 
   * 
   * @param entityId 有关实体的ID
   * @param attrName 要检索的属性的名称。
   * @param `type` 实体类型，以避免在存在多个具有相同实体ID的的情况下出现歧义。
   */
  def 获取属性值(entityId: String, attrName: String, `type`: Option[String] = None): ApiRequest[GetAttributeValueResponse] =
    ApiRequest[GetAttributeValueResponse](ApiMethods.GET, "https://virtserver.swaggerhub.com/ten2net/NGSI/1.0.0", "/v2/entities/{entityId}/attrs/{attrName}/value", "application/json  develop ccthAPI")
      .withQueryParam("type", `type`)
      .withPathParam("entityId", entityId)
      .withPathParam("attrName", attrName)
      .withSuccessResponse[GetAttributeValueResponse](200)
      

}

