/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.GetAttributeDataResponse
import io.swagger.client.model.UpdateAttributeDataRequest
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object AttributesApi {

  /**
   * 删除实体属性。Response： *成功的操作使用204无内容 *错误使用非2xx和(可选)错误有效负载。请参阅\\”错误响应\\“的小节更多细节。
   * 
   * Expected answers:
   *   code 204 :  
   * 
   * @param entityId 实体Id
   * @param attrName 属性名称
   * @param `type` 实体类型，以避免在存在多个具有相同实体ID的的情况下出现歧义。
   */
  def 删除单个属性(entityId: String, attrName: String, `type`: Option[String] = None): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.DELETE, "https://virtserver.swaggerhub.com/ten2net/NGSI/1.0.0", "/v2/entities/{entityId}/attrs/{attrName}", "application/json  develop ccthAPI")
      .withQueryParam("type", `type`)
      .withPathParam("entityId", entityId)
      .withPathParam("attrName", attrName)
      .withSuccessResponse[Unit](204)
        /**
   * 请求有效负载是表示新属性数据的对象。先前的属性数据由请求中的属性数据替换。该对象遵循属性的NSON表示\\ n(在”JSON属性表示“中描述)部分)。响应： *成功的操作使用204无内容 *错误使用非2xx和(可选)错误有效负载。有关更多详细信息，请参阅\\“错误响应\\”小节。
   * 
   * Expected answers:
   *   code 200 :  
   * 
   * @param entityId 要更新的实体的ID
   * @param attrName 属性名称
   * @param contentType 
   * @param body 
   * @param `type` 实体类型，以避免在存在多个具有相同实体ID的的情况下出现歧义。
   */
  def 更新属性数据(entityId: String, attrName: String, contentType: String, body: UpdateAttributeDataRequest, `type`: Option[String] = None): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.PUT, "https://virtserver.swaggerhub.com/ten2net/NGSI/1.0.0", "/v2/entities/{entityId}/attrs/{attrName}", "application/json  develop ccthAPI")
      .withBody(body)
      .withQueryParam("type", `type`)
      .withPathParam("entityId", entityId)
      .withPathParam("attrName", attrName)
      .withHeaderParam("Content-Type", contentType)
      .withSuccessResponse[Unit](200)
        /**
   * 返回带有属性的属性数据的JSON对象。该对象遵循属性的JSON 表示(在”JSON属性表示“部分中描述)。响应： *成功的操作使用200 OK 。 *错误使用非2xx和(可选)错误有效负载。有关更多详细信息，请参阅\\“错误响应\\”小节。
   * 
   * Expected answers:
   *   code 200 : GetAttributeDataResponse 
   * 
   * @param entityId 实体Id
   * @param attrName 要检索的属性的名称。
   * @param `type` 实体类型，以避免在存在多个具有相同实体ID的的情况下出现歧义。
   * @param metadata 要包含在响应中的元数据名称列表。请参阅”过滤掉属性和元数据“部分以获取更多详细信息。
   */
  def 获取属性数据(entityId: String, attrName: String, `type`: Option[String] = None, metadata: Option[String] = None): ApiRequest[GetAttributeDataResponse] =
    ApiRequest[GetAttributeDataResponse](ApiMethods.GET, "https://virtserver.swaggerhub.com/ten2net/NGSI/1.0.0", "/v2/entities/{entityId}/attrs/{attrName}", "application/json  develop ccthAPI")
      .withQueryParam("type", `type`)
      .withQueryParam("metadata", metadata)
      .withPathParam("entityId", entityId)
      .withPathParam("attrName", attrName)
      .withSuccessResponse[GetAttributeDataResponse](200)
      

}

