/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.model.NotifyRequest
import io.swagger.client.model.QueryRequest
import io.swagger.client.model.QueryResponse
import io.swagger.client.model.UpdateRequest
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object BatchOperationsApi {

  /**
   * 响应有效负载是一个数组，每个匹配的实体包含一个对象，如果找到实体，则为空数组&#x60;[]&#x60;。实体遵循JSON实体表示格式(在”\\“部分中描述) JSON实体表示\\“)。有效负载可能包含以下元素(所有这些元素都是可选的)： +&#x60;entities&#x60;：要搜索的entites列表。每个元素由一个JSON对象表示，其中包含个元素： +&#x60;id&#x60;或&#x60;idPattern&#x60;：受影响实体的Id或模式。两者都不能在同一时间使用，但其中一个必须存在。 +&#x60;type&#x60;或&#x60;typePattern&#x60;：要搜索的实体的类型或类型。两者都不能在同时使用。如果省略，则表示“任何实体类型”。 +&#x60;attrs&#x60;：要提供的属性列表(如果没有)指定的，所有属性)。 +&#x60;expression&#x60;：由&#x60;q&#x60;，&#x60;mq&#x60;，&#x60;georel&#x60;，&#x60;geometry&#x60;和&#x60;coords&#x60;组成的表达式(参见上面关于这个f的“List  entities \\”操作) ield)。 +&#x60;metadata&#x60;：要包含在响应中的元数据名称列表。\\ n有关详细信息，请参阅“过滤掉属性和元数据”部分。响应代码： *成功的操作使用200 OK  *错误使用非2xx和(可选)错误有效负载。有关更多详细信息，请参阅“错误响应”部分。
   * 
   * Expected answers:
   *   code 200 : Seq[QueryResponse] 
   * 
   * @param contentType 
   * @param body 
   * @param limit 限制要检索的实体数量。
   * @param offset 跳过一些记录。
   * @param orderBy 排序结果的标准。请参阅”订购结果“部分了解详情。
   * @param options 选项词典
   */
  def query(contentType: String, body: QueryRequest, limit: Option[Double] = None, offset: Option[Double] = None, orderBy: Option[String] = None, options: Option[String] = None): ApiRequest[Seq[QueryResponse]] =
    ApiRequest[Seq[QueryResponse]](ApiMethods.POST, "https://virtserver.swaggerhub.com/ten2net/NGSI/1.0.0", "/v2/op/query", "application/json  develop ccthAPI")
      .withBody(body)
      .withQueryParam("limit", limit)
      .withQueryParam("offset", offset)
      .withQueryParam("orderBy", orderBy)
      .withQueryParam("options", options)
      .withHeaderParam("Content-Type", contentType)
      .withSuccessResponse[Seq[QueryResponse]](200)
        /**
   * 此操作允许在单个批处理操作中创建，更新和/或删除多个实体。有效负载是一个具有两个属性的对象： +&#x60;actionType&#x60;，用于指定要执行的更新操作的类型：要么&#x60;append&#x60;，&#x60;appendStrict&#x60;，&#x60;update&#x60;，\\ n&#x60;delete&#x60;，要么&#x60;replace&#x60;。 +&#x60;entities&#x60;，一个实体数组，每个实体使用JSON实体表示格式指定\\ n(在section \\“JSON Entity Representation \\”)。\\ n这个操作被分成与&#x60;entities&#x60;向量中的实体一样多的单独操作，因此&#x60;actionType&#x60;被执行为每个操作。取决于&#x60;actionType&#x60;，可以完成使用\\ nnregular非批处理操作的映射： *&#x60;append&#x60;：映射到&#x60;POST / v2 / entities&#x60;(如果实体尚不存在)或&#x60;POST / v2 / entities / &lt;id&gt; / attrs&#x60; (如果实体已存在)。\\ n *&#x60;appendStrict&#x60;：映射到&#x60;POST / v2 / entities&#x60;(如果实体尚不存在)或&#x60;POST / v2 / entities / &lt;id&gt; / attrs？options &#x3D; append&#x60;(如果实体已经存在)。 *&#x60;update&#x60;：映射到&#x60;PATCH /v2/entities/&lt;id&gt;/attrs&#x60;.*&#x60;delete&#x60;：映射到&#x60;DELETE / v2 / entities / &lt;id&gt; / attrs / &lt;如果实体中没有包含任何属性，则attrName&gt;&#x60;对实体中包含的每个属性或&#x60;\\到&#x60;DELETE / v2 / entities / &lt;id&gt;&#x60;。 *&#x60;replace&#x60;：映射到&#x60;PUT / v2 / entities / &lt;id&gt; /attrs&#x60;.Response:*成功的操作使用204 No Content。 *错误使用非2xx和(可选)错误有效负载。有关更多详细信息，请参阅“错误响应”部分。
   * 
   * Expected answers:
   *   code 204 :  
   * 
   * @param contentType 
   * @param body 
   * @param options 选项词典
   */
  def update(contentType: String, body: UpdateRequest, options: Option[String] = None): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://virtserver.swaggerhub.com/ten2net/NGSI/1.0.0", "/v2/op/update", "application/json  develop ccthAPI")
      .withBody(body)
      .withQueryParam("options", options)
      .withHeaderParam("Content-Type", contentType)
      .withSuccessResponse[Unit](204)
        /**
   * 此操作旨在使用通知有效负载，以便保留此通知所包含的所有实体数据，并在必要时进行覆盖。\\ n当一个NGSIv2端点订阅另一个NGSIv2端点(联合方案)时，此操作很有用。请求有效负载必须是NGSIv2通知负载。\\ n行为必须与&#x60;POST / v2 / op / update&#x60;完全相同，&#x60;actionType&#x60;等于&#x60;append&#x60;。\\ nResponse代码： *成功的操作使用200 OK  *错误使用非2xx和(可选)错误有效负载。有关更多详细信息，请参阅\\“错误响应\\”小节。
   * 
   * Expected answers:
   *   code 200 :  
   * 
   * @param contentType 
   * @param body 
   * @param options 选项词典
   */
  def 通知(contentType: String, body: NotifyRequest, options: Option[String] = None): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.POST, "https://virtserver.swaggerhub.com/ten2net/NGSI/1.0.0", "/v2/op/notify", "application/json  develop ccthAPI")
      .withBody(body)
      .withQueryParam("options", options)
      .withHeaderParam("Content-Type", contentType)
      .withSuccessResponse[Unit](200)
      

}

