/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class RetrieveApiResourcesResponse (
  /* 指向实体资源的URL */
  entitiesUrl: String,
  /* URL which points to the types resource */
  typesUrl: String,
  /* 指向订阅资源的URL */
  subscriptionsUrl: String,
  /* URL which points to the registrations resource */
  registrationsUrl: String
) extends ApiModel


